"""initial schema

Revision ID: 4dc69f00aae0
Revises: 
Create Date: 2026-07-25 12:06:08.687988
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '4dc69f00aae0'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_store',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=16), nullable=False),
    sa.Column('grupo', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index('ix_config_store_grupo', 'config_store', ['grupo'], unique=False)
    op.create_table('config_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'version', name='uq_config_version')
    )
    op.create_index('ix_config_versions_key', 'config_versions', ['key'], unique=False)
    op.create_table('instituciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('nombre_cnbv', sa.String(length=160), nullable=True),
    sa.Column('categoria', sa.String(length=24), nullable=False),
    sa.Column('tipo_seguro', sa.String(length=16), nullable=False),
    sa.Column('estatus_regulatorio', sa.String(length=200), nullable=True),
    sa.Column('url_sitio', sa.Text(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("categoria IN ('GOBIERNO', 'SOFIPO', 'BANCO_DIGITAL', 'BANCO_TRADICIONAL', 'IFPE')", name='ck_categoria_valido'),
    sa.CheckConstraint("tipo_seguro IN ('SOBERANO', 'IPAB', 'PROSOFIPO', 'NINGUNO')", name='ck_tipo_seguro_valido'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_instituciones_categoria_activa', 'instituciones', ['categoria', 'activa'], unique=False)
    op.create_index(op.f('ix_instituciones_nombre_cnbv'), 'instituciones', ['nombre_cnbv'], unique=False)
    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=60), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.String(length=12), nullable=False),
    sa.Column('metricas', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("estado IN ('EN_CURSO', 'EXITOSO', 'FALLIDO', 'OMITIDO')", name='ck_estado_valido'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_runs_job_inicio', 'job_runs', ['job_id', 'inicio'], unique=False)
    op.create_table('parametros_fiscales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('tasa_retencion_capital', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=False),
    sa.Column('fuente_url', sa.Text(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('tasa_retencion_capital >= 0 AND tasa_retencion_capital <= 100', name='ck_retencion_en_rango'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anio')
    )
    op.create_table('series_economicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave_banxico', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('unidad', sa.String(length=40), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave_banxico')
    )
    op.create_table('banderas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institucion_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=28), nullable=False),
    sa.Column('severidad', sa.String(length=10), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('periodo_dato', sa.Date(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('resuelta_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severidad IN ('AMARILLA', 'ROJA')", name='ck_severidad_valido'),
    sa.CheckConstraint("tipo IN ('IMOR', 'COBERTURA_CARTERA', 'ICAP', 'NICAP', 'APALANCAMIENTO', 'NO_RECOMENDABLE', 'RED_FLAG_TASA', 'GAT_INCONSISTENTE', 'SIN_COBERTURA')", name='ck_tipo_valido'),
    sa.ForeignKeyConstraint(['institucion_id'], ['instituciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_banderas_institucion_activa', 'banderas', ['institucion_id', 'activa'], unique=False)
    op.create_table('fuentes_tasas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institucion_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('requiere_js', sa.Boolean(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('ultima_extraccion_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultimo_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('nivel IN (2, 3)', name='ck_nivel_de_fuente'),
    sa.ForeignKeyConstraint(['institucion_id'], ['instituciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institucion_id', 'url', name='uq_fuente_url')
    )
    op.create_table('indicadores_financieros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institucion_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.Date(), nullable=False),
    sa.Column('imor', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('icap', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('icor', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('nicap_nivel', sa.String(length=4), nullable=True),
    sa.Column('captacion', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cartera_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('capital_contable', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('pasivo_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fuente_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("nicap_nivel IN ('N1', 'N2', 'N3', 'N4')", name='ck_nicap_nivel_valido'),
    sa.ForeignKeyConstraint(['institucion_id'], ['instituciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institucion_id', 'periodo', name='uq_indicador_periodo')
    )
    op.create_index('ix_indicadores_periodo', 'indicadores_financieros', ['periodo'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institucion_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('tipo', sa.String(length=8), nullable=False),
    sa.Column('instrumento', sa.String(length=24), nullable=False),
    sa.Column('plazo_dias', sa.Integer(), nullable=True),
    sa.Column('monto_minimo', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('liquidez', sa.String(length=20), nullable=False),
    sa.Column('penalizacion_retiro', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(tipo = 'VISTA' AND plazo_dias IS NULL) OR (tipo = 'PLAZO' AND plazo_dias IS NOT NULL AND plazo_dias > 0)", name='ck_plazo_coherente_con_tipo'),
    sa.CheckConstraint("instrumento IN ('CETES', 'BONDDIA', 'BONOS_M', 'BONDES_D', 'UDIBONOS', 'PRLV', 'DEPOSITO_SOFIPO', 'DEPOSITO_BANCARIO', 'FONDO_DEUDA', 'MONEDERO_ELECTRONICO')", name='ck_instrumento_valido'),
    sa.CheckConstraint("liquidez IN ('INMEDIATA', 'AL_VENCIMIENTO', 'CON_PENALIZACION')", name='ck_liquidez_valido'),
    sa.CheckConstraint("tipo IN ('VISTA', 'PLAZO')", name='ck_tipo_valido'),
    sa.CheckConstraint('monto_minimo >= 0', name='ck_monto_minimo_no_negativo'),
    sa.ForeignKeyConstraint(['institucion_id'], ['instituciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institucion_id', 'nombre', 'plazo_dias', name='uq_producto_natural'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_productos_institucion_activo', 'productos', ['institucion_id', 'activo'], unique=False)
    op.create_index('ix_productos_plazo', 'productos', ['tipo', 'plazo_dias'], unique=False)
    op.create_table('valores_serie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['serie_id'], ['series_economicas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serie_id', 'fecha', name='uq_valor_serie_fecha')
    )
    op.create_index('ix_valores_serie_fecha', 'valores_serie', ['serie_id', 'fecha'], unique=False)
    op.create_table('tasas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('tasa_nominal', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('gat_nominal', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('gat_real', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('fecha_dato', sa.Date(), nullable=False),
    sa.Column('fuente', sa.String(length=20), nullable=False),
    sa.Column('fuente_url', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('VIGENTE', 'PENDIENTE_REVISION', 'RECHAZADA')", name='ck_estado_valido'),
    sa.CheckConstraint("fuente IN ('MANUAL', 'BANXICO_API', 'CNBV', 'FETCH_DIRIGIDO', 'LLM_RESEARCH')", name='ck_fuente_valido'),
    sa.CheckConstraint('tasa_nominal >= 0', name='ck_tasa_nominal_no_negativa'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id', 'fecha_dato', 'fuente', name='uq_tasa_observacion')
    )
    op.create_index('ix_tasas_vigentes', 'tasas', ['producto_id', 'estado', 'fecha_dato'], unique=False)
    op.create_table('revisiones_tasas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tasa_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('valor_anterior', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('valor_nuevo', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('estado', sa.String(length=12), nullable=False),
    sa.Column('revisor', sa.String(length=80), nullable=True),
    sa.Column('resuelto_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('PENDIENTE', 'APROBADA', 'RECHAZADA')", name='ck_estado_valido'),
    sa.ForeignKeyConstraint(['tasa_id'], ['tasas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_revisiones_estado', 'revisiones_tasas', ['estado'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_revisiones_estado', table_name='revisiones_tasas')
    op.drop_table('revisiones_tasas')
    op.drop_index('ix_tasas_vigentes', table_name='tasas')
    op.drop_table('tasas')
    op.drop_index('ix_valores_serie_fecha', table_name='valores_serie')
    op.drop_table('valores_serie')
    op.drop_index('ix_productos_plazo', table_name='productos')
    op.drop_index('ix_productos_institucion_activo', table_name='productos')
    op.drop_table('productos')
    op.drop_index('ix_indicadores_periodo', table_name='indicadores_financieros')
    op.drop_table('indicadores_financieros')
    op.drop_table('fuentes_tasas')
    op.drop_index('ix_banderas_institucion_activa', table_name='banderas')
    op.drop_table('banderas')
    op.drop_table('series_economicas')
    op.drop_table('parametros_fiscales')
    op.drop_index('ix_job_runs_job_inicio', table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_index(op.f('ix_instituciones_nombre_cnbv'), table_name='instituciones')
    op.drop_index('ix_instituciones_categoria_activa', table_name='instituciones')
    op.drop_table('instituciones')
    op.drop_index('ix_config_versions_key', table_name='config_versions')
    op.drop_table('config_versions')
    op.drop_index('ix_config_store_grupo', table_name='config_store')
    op.drop_table('config_store')
    # ### end Alembic commands ###
